version: '3'

services:

  fastapi:
    build:
      context: ./app_books
      dockerfile: books.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - parser

  parser:
    build:
      context: ./app_parse
      dockerfile: parser.Dockerfile
    ports:
      - "80:8001"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: book_crossing
      POSTGRES_USER: mikalicce
      POSTGRES_PASSWORD: qwerty
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: